name: Merge main into dev
on:
  push:
    branches:
      - main
jobs:
  update-dev:
    permissions: write-all
    name: update-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@users.noreply.github.com'
      
      - name: Check if dev branch exists and create if needed
        run: |
          if git ls-remote --heads origin dev | grep dev; then
            echo "Dev branch exists, checking out"
            git checkout dev
          else
            echo "Dev branch doesn't exist, creating from main"
            git checkout -b dev
          fi
      
      - name: Merge main into dev
        run: |
          git merge main
          echo "Done with merge"
      
      - name: Push to dev
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
